name: Checks

on:
  push:
    branches:
      - main
      - renovate/**
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))

    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          check-latest: true
          node-version: lts/*
      - run: corepack enable
      - run: yarn install
      - run: yarn build --sourcemap
      - uses: actions/upload-artifact@6f51ac03b9356f520e9adb1b1b7802705f340c2b # v4
        with:
          name: build-${{ github.sha }}
          path: build

  check:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))

    name: Check
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          check-latest: true
          node-version: lts/*
      - run: corepack enable
      - run: yarn install
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: build-${{ github.sha }}
          path: build
      - run: yarn check:spelling
      - run: yarn check:types

  quality:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))

    name: Code Quality
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          check-latest: true
          node-version: lts/*
      - run: corepack enable
      - run: yarn install
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: build-${{ github.sha }}
          path: build
      - run: yarn biome ci --error-on-warnings

  test-node:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))

    name: Test Build on Node.js v${{ matrix.node-version }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        node-version: ['18.19', '18.x', '20.x', '22.x', '23.x']
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          check-latest: true
          node-version: ${{ matrix.node-version }}
      - run: corepack enable
      - run: yarn install
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: build-${{ github.sha }}
          path: build
      - run: yarn test

  test-os:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))

    name: Test Build on ${{ matrix.os }}
    needs:
      - build
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - uses: actions/setup-node@39370e3970a6d050c480ffad4ff0ed4d3fdee5af # v4
        with:
          check-latest: true
          node-version: lts/*
      - run: corepack enable
      - run: yarn install
      - uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: build-${{ github.sha }}
          path: build
      - run: yarn test
